### ISSUE TITLE
Unable to find the action

### ISSUE THREAD

**Issue by makunomark** [JantHsueh/get-apk-info-action#1]
My action fails with this error. I was hoping you could help :-)

##[error]An action could not be found at the URI 'https://api.github.com/repos/JantHsueh/get-apk-version-action/tarball/master'

![image](https://user-images.githubusercontent.com/5811391/91527530-9e210700-e90e-11ea-8195-0061818ca03c.png)

**Comment by rjam** [comment]
The action id from the README is wrong, use `uses: JantHsueh/get-apk-info-action@1.0` instead

**Comment by makunomark** [comment]
Thanks @rjam
